#!/usr/bin/env python3
"""Arm C: train the distributed shape h(x) against the SAME observation table the zero-training arms use.

Reuses, on purpose, so there is exactly one forward model and one metric in this line:
  * `roundtrip_h_test`  -- 1-D Reynolds forward, knot parameterization, noise LCG, Gauss-Newton;
  * `inversion_gate`    -- the §4 metric and the three-cell decision (including its refusals).

Budget is taken from the measured round-trip reading, not from hope: 400 steps cost 4.78 s and the
loss was STILL falling, so the default here is 6000 steps with plateau early-stopping, per obs_seed,
8 seeds, and a segment boundary that leaves a resume point instead of a half-written artefact.

Nothing in this file is evidence about the real geometry: the truth is generated by the same 1-D
family it inverts (the self-comparison shape the project bans as proof).
"""
from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))
import inversion_gate as ig
import roundtrip_h_test as rt

SEEDS_DEFAULT = tuple(range(1, 9))


def constant_fit(target, iters=60):
    """Arm K1: one constant h per branch, through the SAME fitter and metric (the §4 denominator)."""
    orig_knots, orig_params = rt.KNOTS, rt.PARAMS
    try:
        # one knot per branch => a constant h on that branch, fitted by the same Gauss-Newton path
        rt.KNOTS = {"stem": (1.0,), "up": (1.0,), "down": (1.0,)}
        rt.PARAMS = [("stem", 0), ("up", 0), ("down", 0)]
        v, hist = rt.gauss_newton(target, [1.0, 1.0, 1.0], iters=iters)
        dof = {"stem": (v[0],), "up": (v[1],), "down": (v[2],)}
    finally:
        rt.KNOTS, rt.PARAMS = orig_knots, orig_params
    flat = {b: (x,) * len(orig_knots[b]) for b, x in
            (("stem", v[0]), ("up", v[1]), ("down", v[2]))}
    return flat, hist


def trained_mlp(target, steps=6000, lr=2.0e-2, patience=300, log_every=500):
    """The trainable arm: per-branch MLP h(x), plateau early-stop, loss curve reported."""
    try:
        import torch
    except Exception as exc:
        return {"ran": False, "why": f"torch unavailable ({type(exc).__name__})"}
    torch.manual_seed(0)
    tgt = torch.tensor(target, dtype=torch.float64)
    nets = {b: torch.nn.Sequential(torch.nn.Linear(1, 16), torch.nn.Tanh(),
                                   torch.nn.Linear(16, 16), torch.nn.Tanh(),
                                   torch.nn.Linear(16, 1)).double() for b in ("stem", "up", "down")}
    ps = [q for n in nets.values() for q in n.parameters()]

    def hnet(branch, fracs):
        x = torch.tensor([[f] for f in fracs], dtype=torch.float64)
        return (1.0 + 0.6 * torch.tanh(nets[branch](x))).squeeze(-1)

    LENGTH = rt.LENGTHS

    def resist(branch, upto):
        nq = rt.NQ_TORCH
        step = LENGTH[branch] * upto / nq
        fr = [(i + 0.5) / nq * upto for i in range(nq)]
        ws = torch.clamp(hnet(branch, fr) * rt.W_REF[branch], min=1.0e-6)
        return (12.0 * rt.MU * step / ws ** 3).sum()

    def observe():
        Rs, Ru, Rd = resist("stem", 1.0), resist("up", 1.0), resist("down", 1.0)
        q_in = rt.P_IN / (Rs + Ru * Rd / (Ru + Rd))
        p_j = rt.P_IN - q_in * Rs
        q_u, q_d = p_j / Ru, p_j / Rd
        vals = {"q_in": q_in, "q_up": q_u, "q_down": q_d, "p_junction": p_j}
        for branch, q, head in (("stem", q_in, rt.P_IN), ("up", q_u, p_j), ("down", q_d, p_j)):
            for f in rt.PROBES:
                start = rt.P_IN if branch == "stem" else p_j
                vals[f"p_{branch}_{f:.2f}"] = start - q * resist(branch, f)
        return torch.stack([vals[k] for k in rt.OBS_ORDER])

    opt = torch.optim.Adam(ps, lr=lr)
    hist, best, best_at, bad, last_gnorm = [], float("inf"), 0, 0, 0.0
    for it in range(steps):
        opt.zero_grad()
        loss_t = ((observe() - tgt) ** 2).sum()
        loss = float(loss_t.item())
        loss_t.backward()
        gnorm = float(sum((p.grad.norm() ** 2).item() for p in ps) ** 0.5)
        opt.step()
        last_gnorm = gnorm
        hist.append(loss)
        if loss < best * (1.0 - 1.0e-6):
            best, best_at = loss, it
            bad = 0
        else:
            bad += 1
            if bad >= patience:
                break
        if it % log_every == log_every - 1:
            print(f"    step {it + 1}: loss={loss:.6e} grad_norm={gnorm:.3e}", flush=True)
    dof_hat = {}
    with torch.no_grad():
        for b in ("stem", "up", "down"):
            knots = hnet(b, list(rt.KNOTS[b]))
            dof_hat[b] = tuple(float(x) for x in knots)
    return {"ran": True, "torch_version": torch.__version__, "steps_run": len(hist),
            "grad_norm_last": last_gnorm,
            "loss_first": hist[0], "loss_last": hist[-1], "loss_best": best, "best_step": best_at,
            "early_stopped": bad >= patience, "trainable_parameters": len(ps),
            "dof_hat_knots": dof_hat}


def main() -> int:
    ap = argparse.ArgumentParser(description="arm C: train h(x) against the shared observation table")
    ap.add_argument("--obs-seeds", default=",".join(str(s) for s in SEEDS_DEFAULT))
    ap.add_argument("--out-root", required=True)
    ap.add_argument("--steps", type=int, default=6000)
    ap.add_argument("--lr", type=float, default=2.0e-2)
    ap.add_argument("--max-seconds", type=float, default=2400.0)
    ap.add_argument("--stdlib-only", action="store_true", help="arms K1 and B only (no torch)")
    args = ap.parse_args()
    seeds = [int(x) for x in args.obs_seeds.split(",") if x.strip()]
    out_root = Path(args.out_root)
    out_root.mkdir(parents=True, exist_ok=True)
    prog = out_root / "progress.txt"
    art = out_root / "inversion_arms.json"
    done = {}
    if art.is_file():
        done = json.loads(art.read_text(encoding="utf-8")).get("per_seed", {})
    t0 = time.perf_counter()
    res = {"kind": "armC_inversion_run", "truth": "same 1-D family => machinery evidence only",
           "steps_budget": args.steps, "lr": args.lr, "per_seed": dict(done),
           "max_seconds": args.max_seconds}
    htrue_fn = ig.dof_fn(rt.H_TRUE)

    def say(line):
        print(line, flush=True)
        with prog.open("a", encoding="utf-8") as fh:
            fh.write(f"{time.strftime('%H:%M:%S')} {line}\n")

    for s in seeds:
        if str(s) in done:
            say(f"seed {s}: already recorded, skipped (resume)")
            continue
        if time.perf_counter() - t0 > args.max_seconds:
            say(f"SEGMENT-END used={time.perf_counter() - t0:.0f}s cap={args.max_seconds:.0f}s "
                f"missing_seeds={[x for x in seeds if str(x) not in res['per_seed']]}")
            break
        ts = time.perf_counter()
        obs = rt.make_noise(rt.forward(rt.H_TRUE), s, rt.NOISE_FRAC)
        target = rt.vec(obs)
        e_k1 = ig.shape_error(ig.dof_fn(constant_fit(target)[0]), htrue_fn)["rel_l2"]
        v_b, hist_b = rt.gauss_newton(target, [1.0] * len(rt.PARAMS))
        dof_b = rt.dof_from_vec(v_b)
        e_b = ig.shape_error(ig.dof_fn(dof_b), htrue_fn)["rel_l2"]
        row = {"obs_seed": s, "e_K1": e_k1, "e_B": e_b, "B_sse_last": hist_b[-1],
               "B_iters": len(hist_b)}
        if args.stdlib_only:
            row["C"] = {"ran": False, "why": "--stdlib-only"}
        else:
            c = trained_mlp(target, steps=args.steps, lr=args.lr)
            if c.get("ran"):
                e_c = ig.shape_error(ig.dof_fn(c["dof_hat_knots"]), htrue_fn)["rel_l2"]
                row["C"] = {k: c[k] for k in ("steps_run", "loss_first", "loss_last", "loss_best",
                                              "best_step", "early_stopped", "trainable_parameters",
                                              "grad_norm_last")}
                # §4bis (c)/(d) need BOTH cells reported, and the training cell's gradient half is
                # only checkable if the number itself is carried out of the loop.
                row["training_cell"] = ig.training_gate(c["loss_first"], c["loss_last"],
                                                        c["grad_norm_last"], orders=3.0)
                row["shape_cell"] = ig.shape_gate(e_b, row["e_C"], factor=0.5)
                row["e_C"] = e_c
                row["throat_C"] = ig.shape_error(ig.dof_fn(c["dof_hat_knots"]), htrue_fn)["throat"]
            else:
                row["C"] = c
        res["per_seed"][str(s)] = row
        art.write_text(json.dumps(res, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        say(f"seed {s}: e_K1={e_k1:.5f} e_B={e_b:.5f} "
            f"e_C={row.get('e_C', float('nan')):.5f} wall={time.perf_counter() - ts:.1f}s")

    ks = [k for k, v in res["per_seed"].items() if "e_C" in v]
    if ks:
        verdict = ig.decide([res["per_seed"][k]["e_K1"] for k in ks],
                            [res["per_seed"][k]["e_B"] for k in ks],
                            [res["per_seed"][k]["e_C"] for k in ks])
        res["verdict"] = verdict
        say(f"GATE status={verdict['status']} refused={verdict.get('refused')} "
            f"cells_ok={verdict.get('cells_ok')} verdict={verdict.get('verdict')}")
    else:
        say("GATE not evaluated: no seed produced arm C yet")
    res["wall_total_s"] = round(time.perf_counter() - t0, 1)
    art.write_text(json.dumps(res, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    say(f"json={art} used={res['wall_total_s']}s seeds_done={len(res['per_seed'])}/{len(seeds)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
